paths:
  output_dir: /home/projects/zeevid/ofirlev/llm/data/mean_dnabert_s
  jobs_dir: /home/projects/zeevid/ofirlev/llm/step_zero/jobs_dnabert_s

data:
  sample_dir_suffix: "-R1"
  output_mode: mean

model:
  pretrained_name: zhihan1996/DNABERT-S
  batch_size: 128
  device: cuda

runtime:
  overwrite: false
  max_bags: null
